theme: jekyll-theme-cayman
title: Mahbub R Maulaa
subtitle: Urban Data Analyst and Writer
description: I am a Research Assistant at the Boston Area Research Initiative (BARI) and a founder of Curiocity Indonesia. My research focus extends to a wide range of topics, including climate issues, housing, transportation, and community development.
